# Generated by Django 3.0.4 on 2020-03-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
